// <auto-generated />
using DogsHouse.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DogsHouse.Infrastructure.Migrations
{
    [DbContext(typeof(DogsDbContext))]
    partial class DogsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DogsHouse.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TailLength")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Brown",
                            Name = "Buddy",
                            TailLength = 15,
                            Weight = 20
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Name = "Max",
                            TailLength = 10,
                            Weight = 25
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            Name = "Bella",
                            TailLength = 12,
                            Weight = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
